services:
  blog-api:
    container_name: blog-api
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    ports:
      - 8080:8080
    depends_on:
      - blog-db
    volumes:
      - .:/app
#    entrypoint: ["mvn", w"spring-boot:run"]
  blog-front:
    build: /home/mohamed/developpement/blog-api-front/
    container_name: blog-front
    ports:
      - 5173:5173
    depends_on:
      - blog-api
    volumes:
      - /home/mohamed/developpement/blog-api-front:/app

  blog-db:
    image: postgres
    volumes:
      - /home/mohamed/databases/blog-api:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456