services:
  blog-api-container:
    image: blog-api
    ports:
      - 8081:8080
    depends_on:
      - blog-db
    env_file: .env

  blog-db:
    image: postgres
    volumes:
      - /home/mohamed/databases/blog-api:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456