services:
  blog-api-container-dev:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    ports:
      - 8081:8080
    depends_on:
      - blog-db
    volumes:
      - .:/app
#    entrypoint: ["mvn", "spring-boot:run"]

  blog-db:
    image: postgres
    volumes:
      - /home/mohamed/databases/blog-api:/var/lib/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=123456